import { Transport } from '../models/transports.model.js';

export const transportsData = [
  // ==================== BUSES ====================
  // HCM -> Đà Lạt
  {
    type: "bus",
    service_name: "Phương Trang FUTA Bus Lines",
    vehicle_type: "Giường nằm",
    departure_location: "Bến xe Miền Đông, TP.HCM",
    arrival_location: "Bến xe Đà Lạt",
    departure_time: "08:00",
    arrival_time: "15:30",
    duration: "7h 30m",
    price: 280000,
    available_seats: 12,
    rating: 4.8,
    total_reviews: 2340,
    amenities: ["WiFi", "Điều hòa", "Nước uống", "Chăn gối"],
    features: [],
    image: "/images/buses/futa.jpg",
    is_active: true,
  },
  {
    type: "bus",
    service_name: "Mai Linh Express",
    vehicle_type: "Ghế ngồi",
    departure_location: "Bến xe Miền Đông, TP.HCM",
    arrival_location: "Bến xe Đà Lạt",
    departure_time: "09:00",
    arrival_time: "16:00",
    duration: "7h",
    price: 250000,
    available_seats: 8,
    rating: 4.6,
    total_reviews: 1890,
    amenities: ["WiFi", "Điều hòa", "Nước uống"],
    features: [],
    image: "/images/buses/mailinh.jpg",
    is_active: true,
  },
  {
    type: "bus",
    service_name: "Thành Bưởi",
    vehicle_type: "Limousine",
    departure_location: "Bến xe Miền Đông, TP.HCM",
    arrival_location: "Bến xe Đà Lạt",
    departure_time: "10:30",
    arrival_time: "17:30",
    duration: "7h",
    price: 350000,
    available_seats: 16,
    rating: 4.9,
    total_reviews: 3120,
    amenities: ["WiFi", "Điều hòa", "Nước uống", "Chăn gối", "Massage", "TV"],
    features: [],
    image: "/images/buses/thanhbuoi.jpg",
    is_active: true,
  },
  {
    type: "bus",
    service_name: "Hoàng Long",
    vehicle_type: "Giường nằm",
    departure_location: "Bến xe Miền Đông, TP.HCM",
    arrival_location: "Bến xe Đà Lạt",
    departure_time: "20:00",
    arrival_time: "03:30",
    duration: "7h 30m",
    price: 260000,
    available_seats: 5,
    rating: 4.5,
    total_reviews: 1560,
    amenities: ["WiFi", "Điều hòa", "Nước uống", "Chăn gối"],
    features: [],
    image: "/images/buses/hoanglong.jpg",
    is_active: true,
  },
  {
    type: "bus",
    service_name: "Kumho Samco",
    vehicle_type: "Ghế ngồi",
    departure_location: "Bến xe Miền Đông, TP.HCM",
    arrival_location: "Bến xe Đà Lạt",
    departure_time: "11:00",
    arrival_time: "18:00",
    duration: "7h",
    price: 240000,
    available_seats: 20,
    rating: 4.4,
    total_reviews: 980,
    amenities: ["Điều hòa", "Nước uống"],
    features: [],
    image: "/images/buses/kumho.jpg",
    is_active: true,
  },

  // HN -> Sapa
  {
    type: "bus",
    service_name: "Sapa Express",
    vehicle_type: "Giường nằm",
    departure_location: "Bến xe Mỹ Đình, Hà Nội",
    arrival_location: "Bến xe Sapa",
    departure_time: "21:00",
    arrival_time: "05:00",
    duration: "8h",
    price: 300000,
    available_seats: 10,
    rating: 4.7,
    total_reviews: 1456,
    amenities: ["WiFi", "Điều hòa", "Nước uống", "Chăn gối"],
    features: [],
    image: "/images/buses/sapa.jpg",
    is_active: true,
  },
  {
    type: "bus",
    service_name: "Phương Trang FUTA Bus Lines",
    vehicle_type: "Limousine",
    departure_location: "Bến xe Mỹ Đình, Hà Nội",
    arrival_location: "Bến xe Sapa",
    departure_time: "22:00",
    arrival_time: "06:00",
    duration: "8h",
    price: 380000,
    available_seats: 14,
    rating: 4.9,
    total_reviews: 2100,
    amenities: ["WiFi", "Điều hòa", "Nước uống", "Chăn gối", "Massage", "TV"],
    features: [],
    image: "/images/buses/futa.jpg",
    is_active: true,
  },

  // HCM -> Nha Trang
  {
    type: "bus",
    service_name: "Phương Trang FUTA Bus Lines",
    vehicle_type: "Giường nằm",
    departure_location: "Bến xe Miền Đông, TP.HCM",
    arrival_location: "Bến xe Nha Trang",
    departure_time: "07:00",
    arrival_time: "16:00",
    duration: "9h",
    price: 320000,
    available_seats: 15,
    rating: 4.7,
    total_reviews: 3450,
    amenities: ["WiFi", "Điều hòa", "Nước uống", "Chăn gối"],
    features: [],
    image: "/images/buses/futa.jpg",
    is_active: true,
  },
  {
    type: "bus",
    service_name: "Mai Linh Express",
    vehicle_type: "Ghế ngồi",
    departure_location: "Bến xe Miền Đông, TP.HCM",
    arrival_location: "Bến xe Nha Trang",
    departure_time: "08:30",
    arrival_time: "17:00",
    duration: "8h 30m",
    price: 280000,
    available_seats: 18,
    rating: 4.5,
    total_reviews: 2340,
    amenities: ["WiFi", "Điều hòa", "Nước uống"],
    features: [],
    image: "/images/buses/mailinh.jpg",
    is_active: true,
  },

  // HN -> Hạ Long
  {
    type: "bus",
    service_name: "Hoàng Long",
    vehicle_type: "Limousine",
    departure_location: "Bến xe Mỹ Đình, Hà Nội",
    arrival_location: "Bến xe Hạ Long",
    departure_time: "06:00",
    arrival_time: "09:30",
    duration: "3h 30m",
    price: 180000,
    available_seats: 12,
    rating: 4.6,
    total_reviews: 1890,
    amenities: ["WiFi", "Điều hòa", "Nước uống", "Chăn gối"],
    features: [],
    image: "/images/buses/hoanglong.jpg",
    is_active: true,
  },
  {
    type: "bus",
    service_name: "Kumho Samco",
    vehicle_type: "Ghế ngồi",
    departure_location: "Bến xe Mỹ Đình, Hà Nội",
    arrival_location: "Bến xe Hạ Long",
    departure_time: "07:00",
    arrival_time: "10:00",
    duration: "3h",
    price: 150000,
    available_seats: 25,
    rating: 4.4,
    total_reviews: 1234,
    amenities: ["Điều hòa", "Nước uống"],
    features: [],
    image: "/images/buses/kumho.jpg",
    is_active: true,
  },

  // ==================== AIRPORT TRANSFERS ====================
  // Tân Sơn Nhất transfers
  {
    type: "airport_transfer",
    service_name: "Mai Linh Airport Transfer",
    vehicle_type: "Sedan 4 chỗ",
    pickup_location: "Sân bay Tân Sơn Nhất",
    dropoff_location: "Quận 1, TP.HCM",
    duration: "30 phút",
    price: 180000,
    rating: 4.7,
    total_reviews: 1234,
    amenities: [],
    features: ["Driver chuyên nghiệp", "Xe đời mới", "Nước uống miễn phí", "WiFi"],
    image: "/images/transfers/sedan.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "Grab Airport",
    vehicle_type: "SUV 7 chỗ",
    pickup_location: "Sân bay Tân Sơn Nhất",
    dropoff_location: "Quận 1, TP.HCM",
    duration: "30 phút",
    price: 280000,
    rating: 4.8,
    total_reviews: 2567,
    amenities: [],
    features: ["Driver chuyên nghiệp", "Xe rộng rãi", "Hành lý nhiều", "WiFi"],
    image: "/images/transfers/suv.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "VIP Limousine Service",
    vehicle_type: "Limousine 9 chỗ",
    pickup_location: "Sân bay Tân Sơn Nhất",
    dropoff_location: "Quận 1, TP.HCM",
    duration: "30 phút",
    price: 450000,
    rating: 4.9,
    total_reviews: 890,
    amenities: [],
    features: ["Driver tiếng Anh", "Ghế massage", "Nước uống cao cấp", "WiFi", "Báo chí"],
    image: "/images/transfers/limousine.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "Budget Transfer",
    vehicle_type: "Sedan 4 chỗ",
    pickup_location: "Sân bay Tân Sơn Nhất",
    dropoff_location: "Quận 1, TP.HCM",
    duration: "35 phút",
    price: 150000,
    rating: 4.5,
    total_reviews: 456,
    amenities: [],
    features: ["Giá rẻ", "Xe đời cũ", "Driver thân thiện"],
    image: "/images/transfers/budget.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "Premium Airport Transfer",
    vehicle_type: "Mercedes E-Class",
    pickup_location: "Sân bay Tân Sơn Nhất",
    dropoff_location: "Quận 1, TP.HCM",
    duration: "25 phút",
    price: 650000,
    rating: 5.0,
    total_reviews: 234,
    amenities: [],
    features: ["Xe sang", "Driver tiếng Anh", "Nước uống cao cấp", "WiFi", "Khăn lạnh", "Báo chí"],
    image: "/images/transfers/premium.jpg",
    is_active: true,
  },

  // Nội Bài transfers
  {
    type: "airport_transfer",
    service_name: "Nội Bài Express",
    vehicle_type: "Sedan 4 chỗ",
    pickup_location: "Sân bay Nội Bài",
    dropoff_location: "Hoàn Kiếm, Hà Nội",
    duration: "45 phút",
    price: 200000,
    rating: 4.6,
    total_reviews: 1567,
    amenities: [],
    features: ["Driver chuyên nghiệp", "Xe đời mới", "Nước uống miễn phí", "WiFi"],
    image: "/images/transfers/sedan.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "Hanoi Airport Shuttle",
    vehicle_type: "SUV 7 chỗ",
    pickup_location: "Sân bay Nội Bài",
    dropoff_location: "Hoàn Kiếm, Hà Nội",
    duration: "40 phút",
    price: 320000,
    rating: 4.7,
    total_reviews: 2134,
    amenities: [],
    features: ["Driver chuyên nghiệp", "Xe rộng rãi", "Hành lý nhiều", "WiFi"],
    image: "/images/transfers/suv.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "Luxury Airport Transfer",
    vehicle_type: "Mercedes S-Class",
    pickup_location: "Sân bay Nội Bài",
    dropoff_location: "Hoàn Kiếm, Hà Nội",
    duration: "35 phút",
    price: 750000,
    rating: 5.0,
    total_reviews: 456,
    amenities: [],
    features: ["Xe sang", "Driver tiếng Anh", "Nước uống cao cấp", "WiFi", "Khăn lạnh", "Báo chí", "Ghế massage"],
    image: "/images/transfers/premium.jpg",
    is_active: true,
  },

  // Đà Nẵng transfers
  {
    type: "airport_transfer",
    service_name: "Danang Airport Taxi",
    vehicle_type: "Sedan 4 chỗ",
    pickup_location: "Sân bay Đà Nẵng",
    dropoff_location: "Hải Châu, Đà Nẵng",
    duration: "20 phút",
    price: 120000,
    rating: 4.5,
    total_reviews: 890,
    amenities: [],
    features: ["Driver chuyên nghiệp", "Xe đời mới", "Nước uống miễn phí"],
    image: "/images/transfers/sedan.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "Beach Resort Transfer",
    vehicle_type: "Limousine 9 chỗ",
    pickup_location: "Sân bay Đà Nẵng",
    dropoff_location: "Hội An",
    duration: "50 phút",
    price: 400000,
    rating: 4.8,
    total_reviews: 1234,
    amenities: [],
    features: ["Driver tiếng Anh", "Ghế massage", "Nước uống cao cấp", "WiFi", "Báo chí"],
    image: "/images/transfers/limousine.jpg",
    is_active: true,
  },

  // Cam Ranh transfers
  {
    type: "airport_transfer",
    service_name: "Nha Trang Airport Shuttle",
    vehicle_type: "SUV 7 chỗ",
    pickup_location: "Sân bay Cam Ranh",
    dropoff_location: "Trung tâm Nha Trang",
    duration: "35 phút",
    price: 250000,
    rating: 4.6,
    total_reviews: 678,
    amenities: [],
    features: ["Driver chuyên nghiệp", "Xe rộng rãi", "Hành lý nhiều", "WiFi"],
    image: "/images/transfers/suv.jpg",
    is_active: true,
  },
  {
    type: "airport_transfer",
    service_name: "Vinpearl Resort Transfer",
    vehicle_type: "Limousine 9 chỗ",
    pickup_location: "Sân bay Cam Ranh",
    dropoff_location: "Vinpearl Nha Trang",
    duration: "40 phút",
    price: 480000,
    rating: 4.9,
    total_reviews: 1123,
    amenities: [],
    features: ["Xe sang", "Driver tiếng Anh", "Nước uống cao cấp", "WiFi", "Khăn lạnh", "Báo chí"],
    image: "/images/transfers/limousine.jpg",
    is_active: true,
  },
];

export async function seedTransports() {
  try {
    // Clear existing transports (only bus and airport_transfer types)
    await Transport.deleteMany({ type: { $in: ['bus', 'airport_transfer'] } });
    console.log('Cleared existing buses and airport transfers');

    // Insert new transports
    const transports = await Transport.insertMany(transportsData);
    console.log(`✅ Seeded ${transports.length} transports successfully (${transports.filter(t => t.type === 'bus').length} buses, ${transports.filter(t => t.type === 'airport_transfer').length} airport transfers)`);

    return transports;
  } catch (error) {
    console.error('Error seeding transports:', error);
    throw error;
  }
}
